name: Release to JIRA
description: A GitHub action to automatically create releases on JIRA.
author: ulasozguler
branding:
  icon: 'edit'
  color: 'blue'
inputs:
  jira_server:
    description: JIRA server
    required: true
  jira_project:
    description: JIRA project
    required: true
  jira_user:
    description: JIRA user
    required: true
  jira_token:
    description: JIRA user token
    required: true
  release_tag:
    description: Github Tag
  github_token:
    description: Github Token
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Get or create Github release
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        gh api \
          --method GET repos/${{ github.repository }}/releases/tags/${{ inputs.release_tag }} \
          --jq .body > notes.md \
        || \
        gh api \
          --method POST repos/${{ github.repository }}/releases \
            -f tag_name='${{ inputs.release_tag }}' \
            -f name='${{ inputs.release_tag }}' \
            -F generate_release_notes=true \
          --jq .body > notes.md
    - name: Update JIRA
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        INPUT_JIRA_SERVER: ${{ inputs.jira_server }}
        INPUT_JIRA_PROJECT: ${{ inputs.jira_project }}
        INPUT_JIRA_USER: ${{ inputs.jira_user }}
        INPUT_JIRA_TOKEN: ${{ inputs.jira_token }}
        INPUT_RELEASE_TAG: ${{ inputs.release_tag }}
      run: python ./src/main.py
